# Generated by scripts/render-formula.sh in smhasan94/rotate from
# packaging/homebrew/rotate.rb.tmpl. The release workflow overwrites this
# file on every release; change the template there instead.
class Rotate < Formula
  desc "Revoke and rotate leaked secrets safely, end to end"
  homepage "https://github.com/smhasan94/rotate"
  license "Apache-2.0"

  on_macos do
    on_arm do
      url "https://github.com/smhasan94/rotate/releases/download/v0.2.0/rotate-0.2.0-aarch64-apple-darwin.tar.gz"
      sha256 "691b07d0e6f094d760ef41a5cfbb0d562e95c716e9e99907504d4873d30ef39b"
    end
    on_intel do
      url "https://github.com/smhasan94/rotate/releases/download/v0.2.0/rotate-0.2.0-x86_64-apple-darwin.tar.gz"
      sha256 "0a486d7390926cd4c78e98b3ace25138d48ae6307659f226a27943f823320550"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/smhasan94/rotate/releases/download/v0.2.0/rotate-0.2.0-aarch64-unknown-linux-gnu.tar.gz"
      sha256 "c55e11e1342cb2616280a6a530a3410db9130e4c3390f0ef7f449e0199d81f31"
    end
    on_intel do
      url "https://github.com/smhasan94/rotate/releases/download/v0.2.0/rotate-0.2.0-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "8b12e4866fadbba13f2125f8402507e4f6f5276020ae1dfc926db5db939ae534"
    end
  end

  def install
    bin.install "rotate"
  end

  test do
    assert_equal "rotate #{version}", shell_output("#{bin}/rotate --version").strip
  end
end
